@startuml
'https://plantuml.com/class-diagram

class Main

package controll{
class Controll
class Gui
class Leaderboard
}

package user{
class User
class Person
}

package Gamemode{
class Gamemode
class Joker
class ModeJeopardy
class ModeNormal
class ModeSurvival
class Questions
}

package csv{
class CSVReader
}

package model{
    package list{
    class List
    }
    package node{
    class Node
    }
    package queue{
    class Queue
    }
    package Stack{
    class Stack
    }
}

class Game{
- user : User
- ctrl : Controll
- csv : CSVReader
- gamemode : Gamemode


+ Game(pCsv : CSVReader, pCtrl : Controll)
+ startGame(pGaemmode : Gamemode) : void
+ setUser() : User
+ setCSV() : void
+ setCtrl() : void
+ setGamemode(pGamemode : Gamemode)
+ getUser() : User
+ getCtrl() : Controll
+ getCsv() : CSVReader
+ getGamemode() : Gamemode
}


class Controll{

- gui : Gui
- leaderboard : Leaderboard
- options : Options
+ getGui() : Gui
+ getLeaderboard() : Leaderboard
+ getOptions() : Options
}

class User{
- points : int

+ setPoints(pPoints : String) : void
+ getPoints() : String
}

abstract class Person{
- name : String
- age : int

+ setName(pName : String) : void
+ setAge(pAge : int) : void
+ getName() : String
+ getAge() : String
}

class Gui{

}

class Leaderboard{
- users : User[10]
+ showleaderboard() : void
 }

class CSVReader{
+ readCSVList(path : String) : List<Questions>
+ readCSVQueue(path : String) : Queue<Questions>
+ readCSVStack(path : String) : Stack<Questions>

}


class Questions{
- question : String
- answers : String[4]
- correct : String
- checkcorrect() : boolean
+ setCorrect() : void
+ setAnswers() : void
+ setQuestion() : void
+ getCorrect() : String
+ setAnswers() : String[]
+ setQuestion() : String
}


class Gamemode{
- joker : Joker[3]
+ getJoker() : Joker[]
+ setJoker() : void
+ useJoker() : void
}

class ModeNormal extends Gamemode{
- questions : List<Questions>
- money : int
+ getQuestions() : List<Questions>
+ setMoney() : void
+ getMoney() : int
}

class ModeSurvival extends Gamemode{
- questions : Stack<Questions>
- counter : int
+ getQuestions() : Stack<Questions>
+ count() : void
+ getCounter() : int
}

class ModeJeopardy extends Gamemode{
- questions : Queue<Questions>
- points : int
+ getQuestions() : Queue<Questions>
+ getPoints() : int
+ setPoints() : void
}

class Node{
- context : T
- next : Node<T>

+ getContext() : T
+ setContext(pContext : T) : void
+ getNext() : Node<T>
+ setNext(pNode : Node<T>) : void
}

class List{
- first : Node<T>
- aktuelleNode : Node<T>

+ isEmpty() : boolean
+ hasAccess() : boolean
+ next() : void
+ toFirst() : void
+ toLast() : void
+ getObject() : T
+ setObject() : void
+ append(pContext : T) : void
+ insert(pContext : T) : void
+ concat(pList : List<T>) : void
+ remove() : void
}

class Stack{
- first : Node<T>

+ isEmpty() : boolean
+ enqueue(pObject : T) : void
+ dequeue() : void
+ front() : T
}

class Queue{
- first : Node<T>

+ isEmpty() : boolean
+ push(pObject : T) : void
+ pop() : void
+ top() : T
}

class Joker{

}

Main *-- Game

Person <|-- User

Node --o Stack
Node --o Queue
Node --o List


@enduml